services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ox
      POSTGRES_PASSWORD: ox
      POSTGRES_DB: oxprocessing
    ports:
      - "5432:5432"
    volumes:
      - oxprocessing_pg:/var/lib/postgresql/data

volumes:
  oxprocessing_pg:
